app/app/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

app/core/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from core import views

urlpatterns = [
    path('', views.home),
    path('signin', views.signin, name='signin'),
    path('signup', views.signup, name='signup'),
    path('signout', views.signout, name='signout'),
    path('account', views.account, name='account'),
    path('accounts/login/', views.accounts_login),
    path('account/editemail', views.editemail, name='editemail'),
    path('account/editpass', views.editpass, name='editpass'),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('report/', views.reports, name="reports"),
    path('reports/new/', views.reports_new, name="reports_new"),
    path('report/<str:pk>/', views.report),
    path('report/<str:pk>/update', views.update_report),
    path('report/<str:pk>/delete', views.delete_report),
    path('create/', views.create_report, name="create"),
    path('report/<str:rid>/delete_attatchment/<str:aid>', views.delete_attachment),
]

app/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Group(models.Model):
    name = models.CharField(max_length=255)
    profiles = models.ManyToManyField(Profile, related_name='profiles')

    def __str__(self):
        return self.name


class Report(models.Model):
    name = models.CharField(max_length=255)
    tags = models.ManyToManyField(Tag)
    groups = models.ManyToManyField(Group)
    author = models.ForeignKey(Profile, on_delete=models.SET_NULL, related_name='author', null=True)
    editors = models.ManyToManyField(Profile, related_name='editors')
    content = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    edited_at = models.DateTimeField(auto_now=True, null=True)
    attachment_ref = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name


class Attachment(models.Model):
    file = models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%D/')
    report = models.ForeignKey(Report, on_delete=models.CASCADE)

app/core/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

from core.models import Profile


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class EditProfileEmail(ModelForm):
    class Meta:
        model = User
        fields = ['email']

app/core/views.py
import os
# import pandas as pd
import openpyxl
import datetime

from django.shortcuts import render, redirect, get_object_or_404
from django.db import transaction
from django.contrib.auth.forms import PasswordChangeForm

from django.contrib import messages

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import Group as UserGroup
from core.models import *
from core.forms import CreateUserForm, EditProfileEmail

from app import settings

# Create your views here.

@login_required(login_url='signin')
def home(request):
    return redirect('reports')

@login_required(login_url='signin')
def reports(request):
    profile = Profile.objects.get(user=request.user)
    user_groups = Group.objects.filter(profiles=profile)
    reports = Report.objects.filter(groups__in=user_groups).order_by('-created_at')
    context = {
        'reports': reports,
    }
    return render(request, 'core/reports.html', context)

@login_required(login_url='signin')
def report(request, pk):
    report = get_object_or_404(Report, id=pk)
    report_groups = Group.objects.filter(report=report).all()
    flag = False
    for group in report_groups:
        obj = Profile.objects.filter(profiles=group).all()
        if Profile.objects.get(user=request.user) in obj:
            flag = True
    if flag == False:
        messages.success(request, 'You have not permission to view the report!')
        return redirect('reports')
    context = {
        'report': report,
    }
    return render(request, 'core/report.html', context)

@login_required(login_url='signin')
def create_report(request):
    if request.method == 'POST':
        try:
            request.POST.get('Name')[0]
            with transaction.atomic():
                report = Report.objects.create(
                    name = request.POST.get('Name'),
                    author = Profile.objects.get(user=request.user),
                    content = request.POST.get('Content'),
                )

                tags = str(request.POST.get('Tags')).split(',')
                for t in tags:
                    tag, created_tag = Tag.objects.get_or_create(name=t)
                    report.tags.add(tag)
                
                groups = request.POST.getlist('Groups')
                for g in groups:
                    group = Group.objects.get(id=int(g))
                    report.groups.add(group)

                report.editors.add(Profile.objects.get(user=request.user))

                files = request.FILES.getlist('Files')
                for file in files:
                    Attachment.objects.create(
                        file = file,
                        report = report
                    )
        except:
            groups = Group.objects.filter(profiles=Profile.objects.get(user=request.user))
            context = { 
                'groups': groups,
                'error': 'Please make sure that you entered valid inputs and try again'
            }

            return render(request, 'core/create_report.html', context)
        messages.success(request, 'Report created successfully')
        return redirect('/report')
    groups = Group.objects.filter(profiles=Profile.objects.get(user=request.user))
    context = { 
        'groups': groups,
    }

    return render(request, 'core/create_report.html', context)

@login_required(login_url='signin')
def update_report(request, pk):
    if request.method == 'POST':
        try:
            request.POST.get('Name')[0]
            with transaction.atomic():
                report = Report.objects.get(id=pk)

                report.name = request.POST.get('Name')
                report.content = request.POST.get('Content')

                report.tags.clear()
                tags = str(request.POST.get('Tags')).split(',')
                for t in tags:
                    tag, created_tag = Tag.objects.get_or_create(name=t)
                    report.tags.add(tag)
                
                report.groups.clear()
                groups = request.POST.getlist('Group')
                groups[0]
                for g in groups:
                    group = Group.objects.get(id=int(g))
                    report.groups.add(group)

                report.editors.add(Profile.objects.get(user=request.user))

                report.save()

                files = request.FILES.getlist('Files')
                for file in files:
                    Attachment.objects.create(
                        file = file,
                        report = report
                    )
        except Exception as e:
            print(e)
            report = get_object_or_404(Report, id=pk)
            report_groups = Group.objects.filter(report=report).all()
            flag = False
            for group in report_groups:
                obj = Profile.objects.filter(profiles=group).all()
                if Profile.objects.get(user=request.user) in obj:
                    flag = True
            if flag == False:
                messages.success(request, 'You have not permission to edit the report!')
                return redirect('reports')
            groups = Group.objects.filter(profiles=Profile.objects.get(user=request.user))
            rgroups = report.groups.all()
            temp3 = []
            for element in rgroups:
                if element not in groups:
                    temp3.append(element)
            dgroups = temp3
            context = { 
                'report': report,
                'groups': groups,
                'rgroups': rgroups,
                'dgroups': dgroups,
                'error': 'Please make sure that you entered valid inputs and try again'
            }

            return render(request, 'core/update_report.html', context)
        # Attachment.objects.create(file=request.FILES.get('Files'))
        messages.success(request, 'The report has been updated successfully')
        return redirect('/report/{}'.format(pk))
    report = get_object_or_404(Report, id=pk)
    report_groups = Group.objects.filter(report=report).all()
    flag = False
    for group in report_groups:
        obj = Profile.objects.filter(profiles=group).all()
        if Profile.objects.get(user=request.user) in obj:
            flag = True
    if flag == False:
        messages.success(request, 'You have not permission to edit the report!')
        return redirect('reports')
    groups = Group.objects.filter(profiles=Profile.objects.get(user=request.user))
    rgroups = report.groups.all()
    temp3 = []
    for element in rgroups:
        if element not in groups:
            temp3.append(element)
    dgroups = temp3
    context = { 
        'report': report,
        'groups': groups,
        'rgroups': rgroups,
        'dgroups': dgroups
    }

    return render(request, 'core/update_report.html', context)

@login_required(login_url='signin')
def delete_report(request, pk):
    report = get_object_or_404(Report, id=pk)
    report_groups = Group.objects.filter(report=report).all()
    flag = False
    for group in report_groups:
        obj = Profile.objects.filter(profiles=group).all()
        if Profile.objects.get(user=request.user) in obj:
            flag = True
    if flag == False:
        messages.success(request, 'You have not permission to delete the report!')
        return redirect('reports')
    report.delete()
    messages.success(request, 'Report deleted successfully')
    return redirect('/report')

@login_required(login_url='signin')
def delete_attachment(request, rid, aid):
    attachment = get_object_or_404(Attachment, id=aid)
    report = get_object_or_404(Report, id=rid)
    report_groups = Group.objects.filter(report=report).all()
    flag = False
    for group in report_groups:
        obj = Profile.objects.filter(profiles=group).all()
        if Profile.objects.get(user=request.user) in obj:
            flag = True
    if flag == False:
        messages.success(request, 'You have not permission to edit the report!')
        return redirect('reports')
    attachment.delete()
    messages.success(request, 'Attachment deleted successfully')
    return redirect('/report/{}/update'.format(rid))

def signin(request):
    if request.user.is_authenticated:
        return redirect('reports')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('reports')
            else:
                context = {'error': 'Invalid username or password'}
                return render(request, 'core/login.html', context= context)

        context = {}
        return render(request, 'core/login.html', context= context)

@login_required(login_url='signin')
def signout(request):
    logout(request)
    return redirect('signin')

def signup(request):
    if request.user.is_authenticated:
        return redirect('reports')
    else:
        form = CreateUserForm()

        if request.method == 'POST':
            try:
                with transaction.atomic():
                    form = CreateUserForm(request.POST)
                    if form.is_valid():
                        form.save()
                        user = form.cleaned_data.get('username')
                        Profile.objects.create(user= User.objects.get(username=user))
                        user_group = UserGroup.objects.get(name='User') 
                        user_group.user_set.add(User.objects.get(username=user))
                        messages.success(request, 'Account was created successfully for '+user)
                        return redirect('signin')
            except:

app/core/templates/core/account.html
{% extends 'core/main.html' %}

{% block content %}

<br>
<br>
<br>

<div style="margin-left: 50%; width:70%; transform: translateX(-50%)">
    {% for message in messages %}
        <div class="" style="color: blue;" role="alert">
            {{message}}
        </div>
    {% endfor %}
    <form method="post" enctype="multipart/form-data" action="{% url 'editemail' %}">
        {% csrf_token %}
        <div class="form-group">
            <br>
            <p><label>To change email</label></p>
            <label for="email">Email:</label>
            <div class="form-outline mb-4">
                {{emailform.email}}
            </div>
            <input type="submit" value="Edit email">
            <hr>
            {{emailform.errors}}
        </div>
    </form>
    <form method="post" enctype="multipart/form-data" action="{% url 'editpass' %}">
        {% csrf_token %}
        <div class="form-group">
            <p><label>To change password</label></p>
            <label for="oldpass">Old Password:</label>
            {{passform.old_password}}
            <label for="password1">New Password:</label>
            {{passform.new_password1}}
            <label for="password2">New Password Confirmation:</label>
            {{passform.new_password2}}
            <input type="submit" value="Edit password">
            <p>{{passform.errors}}</p>
        </div>
    </form>
</div>

<br>
<br>
<br>
<br>
<br>

<script>
    var formFields = document.getElementsByTagName('input')
    formFields[1].classList.add('form-control');
    formFields[1].classList.add('form-control-lg');

    formFields[4].classList.add('form-control');
    formFields[4].classList.add('form-control-lg');

    formFields[5].classList.add('form-control');
    formFields[5].classList.add('form-control-lg');

    formFields[6].classList.add('form-control');
    formFields[6].classList.add('form-control-lg');
</script>

{% endblock %}

app/core/templates/core/create_report.html
{% extends 'core/main.html' %}

{% block content %}

<br>
<br>
<br>

<div style="margin-left: 50%; width:70%; transform: translateX(-50%)">
    {% if error %}
        <div class="alert alert-danger" role="alert">
            {{error}}
        </div>
    {% endif %}
    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <div class="form-group"></div>
            <br>
            <label for="Name">Name*:</label>
            <input class="form-control form-control-lg" type="text" id="Name" name="Name" placeholder="Report Name">
            <hr>
            <label for="Attachments">Attachments:</label>
            <input type="file" class="form-control-file" id="Attachments" name="Files" multiple >
            <hr>
            <label for="Content">Content:</label>
            <textarea class="form-control" id="Content" name="Content" rows="3"></textarea>
            <hr>
            <label for="Tags">Tags (to split between tags use a comma without space):</label>
            <textarea class="form-control" id="Tags" name="Tags" rows="2"></textarea>
            <hr>
            <label for="Groups">Groups*:</label>
            {% for group in groups %}
                <div class="form-check form-check">
                    <input class="form-check-input" type="checkbox" id="Group" value="{{group.id}}" name="Groups">
                    <label class="form-check-label" for="Group">{{group.name}}</label>
                </div>
            {% endfor %}
            <hr>
            <input type="submit" value="Submit">
        </div>
    </form>
</div>

<br>
<br>
<br>
<br>
<br>

{% endblock %}

app/core/templates/core/dashboard.html
{% extends 'core/main.html' %}

{% block content %}
<h1>Dashboard Here</h1>
{% endblock %}

app/core/templates/core/login.html
{% load static %}

<!DOCTYPE html>
    <html lang="en">
        <head>
        <meta charset='utf-8'>
        <meta http-equiv='X-UA-Compatible' content='IE=edge'>
        <title>RMS</title>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script type="text/javascript">
            
        </script>
    </head>
    <body>
        <div style="margin-top:10%; width: 50%; transform: translateX(-50%); margin-left:50%">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{error}}
                </div>
            {% endif %}
            <form method="post" action="{% url 'signin' %}">
                {% csrf_token %}
                <!-- Username -->
                <div class="form-outline mb-4">
                    <label class="form-label" for="form2Example1">Username</label>
                    <input type="text" id="form2Example1" name='username' class="form-control" />
                </div>

                <!-- Password input -->
                <div class="form-outline mb-4">
                    <label class="form-label" for="form2Example2">Password</label>
                    <input type="password" id="form2Example2" name='password' class="form-control" />
                </div>
    
                <!-- Submit button -->
                <input type="submit" value="Sign In">
    
                <!-- Register buttons -->
                <div class="text-center">
                    <p>Don't have an account? <a href="{% url 'signup' %}">Sign Up</a></p>
                </div>
                <div class="text-center">
                    <p>Forget Password? <a href="{% url 'reset_password' %}">Reset Password</a></p>
                </div>
            </form>
            {% for message in messages %}
                <p id="messages" style="color:green">{{message}}</p>
            {% endfor %}
        </div>
    </body>
</html>

app/core/templates/core/main.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>RMS</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <script type="text/javascript" src="{% static 'js/searchName.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/searchContent.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/searchAuthor.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/searchGroup.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/searchEditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/searchTag.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</head>
<body>
    {% include 'core/navbar.html' %}

    {% block content %}
    
    
    
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

app/core/templates/core/navbar.html
<style>
  .hello-msg {
    font-size: 110%;
    margin-right: 1%;
  }
  a:hover{
    text-decoration: underline
  }
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container-fluid">
      <a id="logo" class="navbar-brand" href="/report">Report Management System</a>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item" style="width:7em">
          <a class="" aria-current="page" href="{% url 'account' %}" style="width:7em; color: blue; font-size: 110%;">Edit Profile</a>
        </li>
      </ul>
    </div>
    <div class="hello-msg">
      {{request.user}}
    </div>
    <div class="hello-msg">
      <a href="{% url 'signout' %}" style="color: red;">
        Logout
      </a>
    </div>
</nav>

app/core/templates/core/new_reports.html
{% extends 'core/main.html' %}

{% block content %}

<br>
<br>
<br>

<div style="margin-left: 50%; width:70%; transform: translateX(-50%)">
    {% if error %}
        <div class="alert alert-danger" role="alert">
            {{error}}
        </div>
    {% endif %}
    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <div class="form-group"></div>
            <br>
            <label for="excel">Excel file contains reports information as(attachments_id of report _ attachment name)Like picture:<br>(Mandatory columns are ReportName and ReportGroups)<br>(Row 1 must be same as picture)</label><br>
            <img src="/media/excel.png" style="width:50%"  alt="">
            <input type="file" class="form-control-file" id="excel" name="excel">
            <hr>
            <label for="zip">Upload files like picture below reference attachment to report by adding {Attachments_id from excel file}_ at the begining of the file name:</label>
            <img src="/media/zip.png" style="width:50%" alt="">
            <input type="file" class="form-control-file" id="zip" name="zip" multiple>
            <hr>
            <input type="submit" value="Submit">
        </div>
    </form>
</div>

<br>
<br>
<br>
<br>
<br>

{% endblock %}

app/core/templates/core/report.html
{% extends 'core/main.html' %}

{% block content %}

<br>
<br>
<br>
<br>

<h1 style="transform: translateX(-50%); margin-left:50%">Report</h1>

<a href="update"><button type="button" class="btn btn-light"
        style="width: 50%; transform: translateX(-50%); margin-left:50%; color:blue">Edit the report</button></a>

<a href="delete"><button type="button" class="btn btn-light"
        style="width: 50%; transform: translateX(-50%); margin-left:50%; color:red">Delete the report</button></a>

<br>
<br>

<div class="card" style="width: 80%; transform: translateX(-50%); margin-left:50%">
    {% for message in messages %}
    <div class="alert alert-success" role="alert">
        {{message}}
    </div>
    {% endfor %}
    <div class="card-body">
        <h5 class="card-title name">{{report.name}}</h5>
        <h6 class="card-subtitle mb-2 text-muted">Attachments:</h6>
        <ul class="attachments">
            {% for attachment in report.attachment_set.all %}
                <a href="{{attachment.file.url}}" style= "color: black; text-decoration: none"><li>{{attachment.file.name|slice:"29:"}}</li></a>
            {% endfor %}
        </ul>
        <h6 class="card-subtitle mb-2 text-muted">Tags: {{ report.tags.all|join:', ' }}</h6>
        <h6 class="card-subtitle mb-2 text-muted">Groups: {{ report.groups.all|join:', ' }}</h6>
        <h6 class="card-subtitle mb-2 text-muted">Author: {{report.author}}</h6>
        <h6 class="card-subtitle mb-2 text-muted">Editors: {{ report.editors.all|join:', ' }}</h6>
        <h6 class="card-subtitle mb-2 text-muted">Created: {{report.created_at}}</h6>
        <h6 class="card-subtitle mb-2 text-muted">Last Updated: {{report.edited_at}}</h6>
        <p class="card-text content">{{report.content}}</p>
    </div>
</div>

<br>
<br>
<br>
<br>

{% endblock %}

app/core/templates/core/signup.html
{% load static %}

<!DOCTYPE html>
    <html lang="en">
        <head>
        <meta charset='utf-8'>
        <meta http-equiv='X-UA-Compatible' content='IE=edge'>
        <title>RMS</title>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script type="text/javascript">
            
        </script>
    </head>
    <body>
        <div style="margin-top:10%; width: 50%; transform: translateX(-50%); margin-left:50%">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{error}}
                </div>
            {% endif %}
            <form method="post" action="{% url 'signup' %}">
                {% csrf_token %}

                <!-- Username -->
                <div class="form-outline mb-4">
                    <label class="form-label" for="form2Example1">Username</label>
                    {{form.username}}
                </div>

                <!-- Email -->
                <div class="form-outline mb-4">
                    <label class="form-label" for="form2Example1">Email</label>
                    {{form.email}}
                </div>
    
                <!-- Password input -->
                <div class="form-outline mb-4">
                    <label class="form-label" for="form2Example2">Password</label>
                    {{form.password1}}
                </div>

                <!-- Password confirmation input -->
                <div class="form-outline mb-4">
                    <label class="form-label" for="form2Example2">Re-enter Password</label>
                    {{form.password2}}
                </div>

                <input type="submit" value="Create User">
    
                <!-- Register buttons -->
                <div class="text-center">
                    <p>Already have an account? <a href="{% url 'signin' %}">Sign in</a></p>
                </div>
            </form>
            {{form.errors}}
        </div>
        <script>
            var formFields = document.getElementsByTagName('input')
            formFields[1].classList.add('form-control');
            formFields[2].classList.add('form-control');
            formFields[3].classList.add('form-control');
            formFields[4].classList.add('form-control');
        </script>
    </body>
</html>

app/core/templates/core/update_report.html
{% extends 'core/main.html' %}

{% block content %}

<br>
<br>
<br>

<div style="margin-left: 50%; width:70%; transform: translateX(-50%)">
    {% if error %}
        <div class="alert alert-danger" role="alert">
            {{error}}
        </div>
    {% endif %}
    {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{message}}
        </div>
    {% endfor %}
    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <div class="form-group"></div>
            <br>
            <label for="Name">Name*:</label>
            <input class="form-control form-control-lg" type="text" value="{{report.name}}" id="Name" name="Name" placeholder="Report Name">
            <hr>
            <label for="Attachment">Attachments:</label>
            <ul class="attachments">
                {% for attachment in report.attachment_set.all %}
                <a href="{{attachment.file.url}}" style="color: black; text-decoration: none">
                    <li>{{attachment.file.name|slice:"29:"}}</li>
                </a><a href="delete_attatchment/{{attachment.id}}" style="color: red; text-decoration: none">delete
                    attachment</a>
                {% endfor %}
            </ul>
            <label for="Attachments">Add attachment</label>
            <input type="file" class="form-control-file" id="Attachments" name="Files" multiple >
            <hr>
            <label for="Content">Content:</label>
            <textarea class="form-control" id="Content" name="Content" rows="3">{{report.content}}</textarea>
            <hr>
            <label for="Tags">Tags (to split between tags use a comma without space):</label>
            <textarea class="form-control" id="Tags" name="Tags" rows="2">{{ report.tags.all|join:',' }}</textarea>
            <hr>
            <label for="Groups">Groups*:</label>
            {% for group in groups %}
                {% if group in rgroups %}
                <div class="form-check form-check">
                    <input class="form-check-input" type="checkbox" id="Group" name="Group" value="{{group.id}}" checked>
                    <label class="form-check-label" for="Group">{{group.name}}</label>
                </div>
                {% endif %}
                {% if group not in rgroups %}
                <div class="form-check form-check">
                    <input class="form-check-input" type="checkbox" id="Group" name="Group" value="{{group.id}}">
                    <label class="form-check-label" for="Group">{{group.name}}</label>
                </div>
                {% endif %}
            {% endfor %}
            {% for dgroup in dgroups %}
                <div class="form-check form-check">
                    <input class="form-check-input" type="checkbox" id="Group" name="Group" value="{{group.id}}" disabled checked>
                    <label class="form-check-label" for="Group">{{dgroup.name}} (you have not permission to edit this group)</label>
                </div>
            {% endfor %}
            <hr>
            <input type="submit" value="Submit">
        </div>
    </form>
</div>

<br>
<br>
<br>
<br>
<br>

{% endblock %}